# Generated by Django 3.2.6 on 2021-09-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210831_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ('-rank', 'role', 'pk')},
        ),
    ]
