# Generated by Django 3.2.6 on 2021-09-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_credit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='credit',
            name='role',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('caption', models.TextField(blank=True)),
                ('rank', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ('-rank', 'caption', 'pk'),
            },
        ),
    ]
